# Example 7
#
# Pulling out all the stops with cluster of seven Vagrant boxes.
#
domain   = 'example.com'

nodes = [
  { :hostname => 'ex7proxy',   :ip => '192.168.0.40', :box => 'ansibleDebian' },
  { :hostname => 'ex7db',      :ip => '192.168.0.41', :box => 'asnibleCentos6' },
  { :hostname => 'ex7web1',    :ip => '192.168.0.42', :box => 'ansibleDebian' },
  { :hostname => 'ex7web2',    :ip => '192.168.0.43', :box => 'asnibleCentos6' },
  { :hostname => 'ex7static1', :ip => '192.168.0.44', :box => 'ansibleDebian' },
  { :hostname => 'ex7static2', :ip => '192.168.0.45', :box => 'asnibleCentos6' },
  { :hostname => 'ex7cache',   :ip => '192.168.0.46', :box => 'ansibleDebian' },
]

Vagrant::Config.run do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = node[:box]
      node_config.vm.host_name = node[:hostname] + '.' + domain
      node_config.vm.network :hostonly, node[:ip]
      
      memory = node[:ram] ? node[:ram] : 256;
      node_config.vm.customize [
        'modifyvm', :id,
        '--name', node[:hostname],
        '--memory', memory.to_s
      ]
    end
  end
end
