---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  user: vagrant
  sudo: True

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  user: vagrant
  sudo: True

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  user: vagrant 
  sudo: True
  roles:
    - db
